using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Signavex.Domain.Analysis;
using Signavex.Domain.Configuration;
using Signavex.Domain.Interfaces;
using Signavex.Domain.Models;

namespace Signavex.Infrastructure.Anthropic;

public class AnthropicBriefGenerator : IAiBriefGenerator
{
    private readonly HttpClient _httpClient;
    private readonly AnthropicOptions _options;
    private readonly ILogger<AnthropicBriefGenerator> _logger;

    public AnthropicBriefGenerator(
        HttpClient httpClient,
        IOptions<AnthropicOptions> options,
        ILogger<AnthropicBriefGenerator> logger)
    {
        _httpClient = httpClient;
        _options = options.Value;
        _logger = logger;
    }

    public async Task<(string Title, string Content)> GenerateDailyBriefAsync(
        DailyBriefContext context, CancellationToken ct = default)
    {
        var systemPrompt = BuildSystemPrompt();
        var userMessage = BuildUserMessage(context);

        var requestBody = new
        {
            model = _options.Model,
            max_tokens = _options.MaxTokens,
            system = systemPrompt,
            messages = new[]
            {
                new { role = "user", content = userMessage }
            }
        };

        var json = JsonSerializer.Serialize(requestBody, JsonOptions);
        var request = new HttpRequestMessage(HttpMethod.Post, "/v1/messages")
        {
            Content = new StringContent(json, Encoding.UTF8, "application/json")
        };
        request.Headers.Add("x-api-key", _options.ApiKey);
        request.Headers.Add("anthropic-version", "2023-06-01");

        var response = await _httpClient.SendAsync(request, ct);
        response.EnsureSuccessStatusCode();

        var responseJson = await response.Content.ReadAsStringAsync(ct);
        var result = JsonSerializer.Deserialize<AnthropicResponse>(responseJson, JsonOptions);

        var text = result?.Content?.FirstOrDefault(c => c.Type == "text")?.Text
            ?? throw new InvalidOperationException("No text content in Anthropic response");

        // Extract title from first markdown heading, or generate a default
        var title = ExtractTitle(text, context);
        var content = text;

        _logger.LogInformation("Generated daily brief: {Title} ({Length} chars)", title, content.Length);
        return (title, content);
    }

    private static string BuildSystemPrompt()
    {
        return """
            You are Signavex AI, a financial market analyst that writes clear, insightful daily briefings.
            Your job is to interpret economic data and stock scan results in plain English that any investor can understand.

            Write in a professional but accessible tone. Use specific numbers and data points to support your analysis.
            Be honest about uncertainty — if data is mixed, say so. Never give specific buy/sell recommendations.

            Format your output as a markdown blog post with these sections:
            1. A compelling headline (as an H1 heading)
            2. ## What's Happening — a punchy, conversational 2-3 paragraph summary written like you're
               catching a friend up at the water cooler. No jargon, no hedge-fund speak. Write it the way
               someone would actually explain it: "So here's the deal..." This section should stand on its
               own — if someone only reads this part, they walk away understanding the day. Think shareable,
               quotable, the kind of thing someone screenshots and posts. Use plain language, short sentences,
               and a confident-but-not-cocky voice.
            3. ## Market Overview — today's market conditions and what the market multiplier means
            4. ## Economic Health: [Score]/100 — [Label] — category-by-category analysis
            5. ## Stock Opportunities — analyze surfaced candidates or explain why none appeared
            6. ## Correlation Watch — active patterns in plain English
            7. ## What to Watch — forward-looking bullets based on trends
            8. ## Bottom Line — 1-paragraph overall outlook

            End with: ---\n*Generated by Signavex AI · [Date] · Not financial advice*

            Important rules:
            - Use the actual data provided; never fabricate numbers
            - If a section has no data, briefly explain why and move on
            - Keep the total length between 1000-1800 words
            - The "What's Happening" section is the hook — make it engaging enough to share on social media
            - The detailed sections below it are for people who want to dig deeper
            - Write for someone who reads the Wall Street Journal, not a PhD economist
            """;
    }

    private static string BuildUserMessage(DailyBriefContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"Today's date: {context.Date:MMMM d, yyyy}");
        sb.AppendLine();

        // Market context from latest scan
        if (context.LatestScan is not null)
        {
            var scan = context.LatestScan;
            sb.AppendLine("=== LATEST STOCK SCAN ===");
            sb.AppendLine($"Scan completed: {scan.CompletedAtUtc:yyyy-MM-dd HH:mm} UTC");
            sb.AppendLine($"Market Multiplier: {scan.MarketContext.Multiplier:F2}");
            sb.AppendLine($"Market Summary: {scan.MarketContext.Summary}");
            sb.AppendLine($"Total stocks evaluated: {scan.TotalEvaluated}");
            sb.AppendLine($"Candidates surfaced: {scan.Candidates.Count}");
            sb.AppendLine($"Errors: {scan.ErrorCount}");
            sb.AppendLine();

            // Market-level signals
            sb.AppendLine("Market-Level Signals:");
            foreach (var signal in scan.MarketContext.MarketSignals)
            {
                sb.AppendLine($"  - {signal.SignalName}: {signal.Score:F2} — {signal.Reason}");
            }
            sb.AppendLine();

            // Surfaced candidates
            if (scan.Candidates.Count > 0)
            {
                sb.AppendLine("Surfaced Candidates:");
                foreach (var candidate in scan.Candidates.Take(10))
                {
                    sb.AppendLine($"  {candidate.Ticker} ({candidate.CompanyName}) — Final Score: {candidate.FinalScore:F2}, Raw: {candidate.RawScore:F2}");
                    foreach (var signal in candidate.SignalResults)
                    {
                        sb.AppendLine($"    {signal.SignalName}: {signal.Score:F2} — {signal.Reason}");
                    }
                }
            }
            else
            {
                sb.AppendLine("No candidates surfaced today (none met the scoring threshold).");
            }
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("=== STOCK SCAN: No scan data available for today ===");
            sb.AppendLine();
        }

        // Scan history / trend
        if (context.RecentScans.Count > 0)
        {
            sb.AppendLine("=== RECENT SCAN HISTORY (last 30 days) ===");
            foreach (var scan in context.RecentScans.Take(10))
            {
                sb.AppendLine($"  {scan.CompletedAtUtc:yyyy-MM-dd}: Multiplier={scan.MarketMultiplier:F2}, Candidates={scan.CandidateCount}, Evaluated={scan.TotalEvaluated}");
            }
            sb.AppendLine();
        }

        if (context.MultiplierTrend.Count > 0)
        {
            sb.AppendLine("Market Multiplier Trend (30 days):");
            foreach (var (date, mult) in context.MultiplierTrend.TakeLast(10))
            {
                sb.AppendLine($"  {date:yyyy-MM-dd}: {mult:F2}");
            }
            sb.AppendLine();
        }

        // Economic health
        if (context.EconomicHealth is not null)
        {
            var health = context.EconomicHealth;
            sb.AppendLine("=== ECONOMIC HEALTH ===");
            sb.AppendLine($"Overall Score: {health.OverallScore}/100 ({health.ScoreLabel})");
            sb.AppendLine();

            sb.AppendLine("Category Scores:");
            foreach (var cat in health.CategoryScores)
            {
                sb.AppendLine($"  {cat.CategoryName}: {cat.Score:F0}/100 (trend: {cat.Trend})");
            }
            sb.AppendLine();

            if (health.KeyInsights.Count > 0)
            {
                sb.AppendLine("Key Insights:");
                foreach (var insight in health.KeyInsights)
                {
                    sb.AppendLine($"  [{insight.Type}] {insight.Title}: {insight.Message}");
                }
                sb.AppendLine();
            }
        }

        // Individual indicators
        if (context.Indicators.Count > 0)
        {
            sb.AppendLine("=== ECONOMIC INDICATORS ===");
            foreach (var ind in context.Indicators)
            {
                sb.AppendLine($"  {ind.Name} ({ind.SeriesId}): {ind.FormattedValue}");
                sb.AppendLine($"    Trend: {ind.TrendDirection}, Change: {ind.FormattedChange}, Sentiment: {ind.Sentiment} ({ind.Severity})");
                sb.AppendLine($"    Assessment: {ind.CurrentAssessment}");
                sb.AppendLine($"    Implications: {ind.Implications}");
                if (ind.BenchmarkComparison is not null)
                    sb.AppendLine($"    Benchmark: {ind.BenchmarkComparison}");
            }
            sb.AppendLine();
        }

        // Correlation patterns
        if (context.Correlations?.Patterns.Count > 0)
        {
            sb.AppendLine("=== CORRELATION PATTERNS ===");
            sb.AppendLine($"Overall Risk Level: {context.Correlations.OverallRisk}");
            sb.AppendLine($"Summary: {context.Correlations.Summary}");
            sb.AppendLine();
            foreach (var pattern in context.Correlations.Patterns)
            {
                sb.AppendLine($"  {pattern.Title} (confidence: {pattern.Confidence}%, severity: {pattern.Severity})");
                sb.AppendLine($"    {pattern.Description}");
                sb.AppendLine($"    Signal: {pattern.EconomicSignal}");
                sb.AppendLine($"    Historical context: {pattern.HistoricalContext}");
            }
            sb.AppendLine();
        }

        // Action recommendations
        if (context.ActionPlan is not null)
        {
            sb.AppendLine("=== ACTION RECOMMENDATIONS ===");
            sb.AppendLine($"Outlook: {context.ActionPlan.EconomicOutlook}");
            sb.AppendLine($"Summary: {context.ActionPlan.Summary}");
            foreach (var rec in context.ActionPlan.Recommendations.Take(5))
            {
                sb.AppendLine($"  [{rec.Priority}] {rec.Title}: {rec.Description}");
            }
        }

        return sb.ToString();
    }

    private static string ExtractTitle(string markdown, DailyBriefContext context)
    {
        // Look for first H1 heading
        foreach (var line in markdown.Split('\n'))
        {
            var trimmed = line.TrimStart();
            if (trimmed.StartsWith("# "))
            {
                return trimmed[2..].Trim();
            }
        }

        return $"Daily Market Brief — {context.Date:MMMM d, yyyy}";
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    private sealed class AnthropicResponse
    {
        [JsonPropertyName("content")]
        public List<ContentBlock>? Content { get; set; }
    }

    private sealed class ContentBlock
    {
        [JsonPropertyName("type")]
        public string Type { get; set; } = string.Empty;

        [JsonPropertyName("text")]
        public string? Text { get; set; }
    }
}
