// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Signavex.Infrastructure.Persistence;

#nullable disable

namespace Signavex.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SignavexDbContext))]
    [Migration("20260302195707_AddDailyBriefTable")]
    partial class AddDailyBriefTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.DailyBriefEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EconomicHealthScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketOutlook")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyBriefs", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.EconomicObservationEntity", b =>
                {
                    b.Property<string>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("SeriesId", "Date");

                    b.HasIndex("SeriesId");

                    b.ToTable("EconomicObservations", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.EconomicSeriesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonalAdjustment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .IsUnique();

                    b.ToTable("EconomicSeries", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.EconomicSyncTrackerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId")
                        .IsUnique();

                    b.ToTable("EconomicSyncTrackers", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanCandidateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("FinalScore")
                        .HasColumnType("REAL");

                    b.Property<double>("RawScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignalResultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ticker");

                    b.HasIndex("ScanRunId", "Ticker")
                        .IsUnique();

                    b.ToTable("ScanCandidates", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanCheckpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatesFound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentTicker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Evaluated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanCheckpoints", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanCommandEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickedUpAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.ToTable("ScanCommands", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MarketMultiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("MarketSignalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalEvaluated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("ScanId")
                        .IsUnique();

                    b.ToTable("ScanRuns", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.EconomicObservationEntity", b =>
                {
                    b.HasOne("Signavex.Infrastructure.Persistence.Entities.EconomicSeriesEntity", "Series")
                        .WithMany("Observations")
                        .HasForeignKey("SeriesId")
                        .HasPrincipalKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanCandidateEntity", b =>
                {
                    b.HasOne("Signavex.Infrastructure.Persistence.Entities.ScanRunEntity", "ScanRun")
                        .WithMany("Candidates")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.EconomicSeriesEntity", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanRunEntity", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
