// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Signavex.Infrastructure.Persistence;

#nullable disable

namespace Signavex.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SignavexDbContext))]
    [Migration("20260302022021_AddWorkerSplitSchema")]
    partial class AddWorkerSplitSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanCandidateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("FinalScore")
                        .HasColumnType("REAL");

                    b.Property<double>("RawScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignalResultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ticker");

                    b.HasIndex("ScanRunId", "Ticker")
                        .IsUnique();

                    b.ToTable("ScanCandidates", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanCheckpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatesFound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentTicker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Evaluated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanCheckpoints", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanCommandEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickedUpAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.ToTable("ScanCommands", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MarketMultiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("MarketSignalsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalEvaluated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("ScanId")
                        .IsUnique();

                    b.ToTable("ScanRuns", (string)null);
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanCandidateEntity", b =>
                {
                    b.HasOne("Signavex.Infrastructure.Persistence.Entities.ScanRunEntity", "ScanRun")
                        .WithMany("Candidates")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("Signavex.Infrastructure.Persistence.Entities.ScanRunEntity", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
