using System.Net;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Signavex.Domain.Analysis;
using Signavex.Domain.Configuration;
using Signavex.Domain.Models;
using Signavex.Infrastructure.Anthropic;
using Signavex.Infrastructure.Tests.Helpers;

namespace Signavex.Infrastructure.Tests.Anthropic;

public class AnthropicBriefGeneratorTests
{
    private const string ValidResponse = """
    {
        "id": "msg_test123",
        "type": "message",
        "role": "assistant",
        "content": [
            {
                "type": "text",
                "text": "# Markets Hold Steady as Fed Signals Patience\n\n## Market Overview\nThe market multiplier sits at 0.85, indicating cautious conditions.\n\n## Economic Health: 65/100 — Fair\nThe economy shows mixed signals.\n\n## Stock Opportunities\nNo candidates surfaced today.\n\n## Correlation Watch\nNo active patterns.\n\n## What to Watch\n- Employment data next week\n\n## Bottom Line\nMarkets are in a wait-and-see mode.\n\n---\n*Generated by Signavex AI · March 1, 2025 · Not financial advice*"
            }
        ],
        "model": "claude-sonnet-4-20250514",
        "stop_reason": "end_turn",
        "usage": { "input_tokens": 500, "output_tokens": 200 }
    }
    """;

    private static AnthropicBriefGenerator CreateGenerator(MockHttpMessageHandler handler)
    {
        var httpClient = new HttpClient(handler) { BaseAddress = new Uri("https://api.anthropic.com") };
        var options = Options.Create(new AnthropicOptions
        {
            ApiKey = "test-api-key",
            Model = "claude-sonnet-4-20250514",
            MaxTokens = 4096
        });
        return new AnthropicBriefGenerator(httpClient, options, NullLogger<AnthropicBriefGenerator>.Instance);
    }

    private static DailyBriefContext CreateMinimalContext()
    {
        return new DailyBriefContext(
            LatestScan: null,
            RecentScans: Array.Empty<ScanSummary>(),
            MultiplierTrend: Array.Empty<(DateTime, double)>(),
            EconomicHealth: null,
            Indicators: Array.Empty<IndicatorInterpretation>(),
            Correlations: null,
            ActionPlan: null,
            Date: new DateOnly(2025, 3, 1));
    }

    [Fact]
    public async Task GenerateDailyBriefAsync_ValidResponse_ReturnsTitleAndContent()
    {
        var handler = new MockHttpMessageHandler(ValidResponse);
        var generator = CreateGenerator(handler);

        var (title, content) = await generator.GenerateDailyBriefAsync(CreateMinimalContext());

        Assert.Equal("Markets Hold Steady as Fed Signals Patience", title);
        Assert.Contains("## Market Overview", content);
        Assert.Contains("## Economic Health", content);
        Assert.Contains("Not financial advice", content);
    }

    [Fact]
    public async Task GenerateDailyBriefAsync_SendsCorrectHeaders()
    {
        var handler = new MockHttpMessageHandler(ValidResponse);
        var generator = CreateGenerator(handler);

        await generator.GenerateDailyBriefAsync(CreateMinimalContext());

        Assert.NotNull(handler.LastRequest);
        Assert.Equal("https://api.anthropic.com/v1/messages", handler.LastRequest!.RequestUri!.ToString());
        Assert.Contains("test-api-key", handler.LastRequest.Headers.GetValues("x-api-key"));
        Assert.Contains("2023-06-01", handler.LastRequest.Headers.GetValues("anthropic-version"));
    }

    [Fact]
    public async Task GenerateDailyBriefAsync_IncludesModelInRequest()
    {
        var handler = new MockHttpMessageHandler(ValidResponse);
        var generator = CreateGenerator(handler);

        await generator.GenerateDailyBriefAsync(CreateMinimalContext());

        Assert.NotNull(handler.LastRequest);
        var body = await handler.LastRequest!.Content!.ReadAsStringAsync();
        Assert.Contains("claude-sonnet-4-20250514", body);
    }

    [Fact]
    public async Task GenerateDailyBriefAsync_ApiError_Throws()
    {
        var handler = new MockHttpMessageHandler("Server Error", HttpStatusCode.InternalServerError);
        var generator = CreateGenerator(handler);

        await Assert.ThrowsAsync<HttpRequestException>(
            () => generator.GenerateDailyBriefAsync(CreateMinimalContext()));
    }

    [Fact]
    public async Task GenerateDailyBriefAsync_WithScanData_IncludesInPrompt()
    {
        var handler = new MockHttpMessageHandler(ValidResponse);
        var generator = CreateGenerator(handler);

        var context = new DailyBriefContext(
            LatestScan: new CompletedScanResult(
                "scan-1", DateTime.UtcNow,
                new MarketContext(0.85, "Cautious conditions",
                    new[] { new SignalResult("MarketTrend", 0.7, 2.0, "Neutral trend", true) }),
                Array.Empty<StockCandidate>(), 500, 2),
            RecentScans: Array.Empty<ScanSummary>(),
            MultiplierTrend: Array.Empty<(DateTime, double)>(),
            EconomicHealth: null,
            Indicators: Array.Empty<IndicatorInterpretation>(),
            Correlations: null,
            ActionPlan: null,
            Date: new DateOnly(2025, 3, 1));

        await generator.GenerateDailyBriefAsync(context);

        var body = await handler.LastRequest!.Content!.ReadAsStringAsync();
        Assert.Contains("Market Multiplier", body);
        Assert.Contains("0.85", body);
        Assert.Contains("Cautious conditions", body);
    }

    [Fact]
    public async Task GenerateDailyBriefAsync_NoH1InResponse_UsesFallbackTitle()
    {
        var noHeadingResponse = """
        {
            "content": [
                {
                    "type": "text",
                    "text": "Today's market showed mixed signals with moderate activity."
                }
            ]
        }
        """;

        var handler = new MockHttpMessageHandler(noHeadingResponse);
        var generator = CreateGenerator(handler);

        var (title, _) = await generator.GenerateDailyBriefAsync(CreateMinimalContext());

        Assert.Equal("Daily Market Brief — March 1, 2025", title);
    }
}
